ka_ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('products.urls')),
]

products/urls.py
from django.urls import path
from . import views


app_name = 'products'

urlpatterns = [
    path('', views.product_list, name='list'),
    path('create/', views.product_create, name='create'),
    path('<str:slug>/', views.product_detail, name='detail'),
    path('<str:slug>/update/', views.product_update, name='update'),
    path('<str:slug>/delete/', views.product_delete, name='delete'),
]

products/models.py
from django.db import models


class Product(models.Model):
    name = models.CharField(max_length=50)
    price = models.FloatField()
    slug = models.SlugField()

    def __str__(self):
        return self.name

products/forms.py
from django.forms import ModelForm
from .models import Product


class ProductCreateForm(ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'slug', 'price']

products/views.py
from django.shortcuts import render, redirect
from .models import Product
from .forms import ProductCreateForm


def product_list(request):
    products = Product.objects.all()
    return render(request, 'products/product_list.html', {'products':products})

def product_detail(request, slug):
    product = Product.objects.get(slug=slug)
    return render(request, 'products/product_detail.html', {'product':product})

def product_create(request):
    if request.method == 'POST':
        form = ProductCreateForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('products:list')
    else:
        form = ProductCreateForm()
    return render(request, 'products/product_create.html', {'form':form})

def product_update(request, slug):
    product = Product.objects.get(slug=slug)
    if request.method == 'POST':
        form = ProductCreateForm(request.POST, instance=product)
        if form.is_valid():
            form.save()
            return redirect('products:list')
    else:
        form = ProductCreateForm(instance=product)
    return render(request, 'products/product_update.html', {'form':form})

def product_delete(request, slug):
    product = Product.objects.get(slug=slug)
    product.delete()
    return redirect('products:list')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

templates/products/product_create.html
{% extends 'base.html' %}

{% block content %}
<a href="{% url 'products:list' %}">Go back</a>
<form action="" method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Create</button>
</form>
{% endblock %}

templates/products/product_detail.html
{% extends 'base.html' %}

{% block content %}
<a href="{% url 'products:list' %}">Go back</a> <br>
<a href="{% url 'products:update' product.slug %}">Edit</a>
<a href="{% url 'products:delete' product.slug %}">delete</a>
<div>
    <h1>{{ product.name }}</h1>
    <p>{{ product.price }}</p>
</div>
{% endblock %}

templates/products/product_list.html
{% extends 'base.html' %}

{% block content %}
<h1>Welcome to the product page</h1>
<a href="{% url 'products:create' %}">Create</a>
{% for product in products %}
<div>
    <h1><a href="{% url 'products:detail' product.slug %}">{{ product.name }}</a></h1>
    <p>{{ product.price }}</p>
</div>
{% endfor %}
{% endblock %}

templates/products/product_update.html
{% extends 'base.html' %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Update</button>
</form>
{% endblock %}